theme: jekyll-theme-cayman
logo: /devops-thumb.png
title: Курс обучения DevOps от Евгения Быкова
description: Девять тем от Linux до Kubernetes и GitOps. Теория простым языком, вопросы с ответами и практика на сквозном проекте
email: jenyabykov322@yandex.ru
github_username: distinguished-sre
show_downloads: false
lang: ru
